name: 'ecommerce_lakehouse'
version: '1.0.0'
config-version: 2

# Tên profile phải khớp với tên định nghĩa trong file profiles.yml
profile: 'ecommerce_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_lakehouse:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
